name: Node.js Build With Yarn
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Yarn Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g yarn
      - run: yarn install
      - run: yarn run build
